/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package city_bookshop;

import java.awt.EventQueue;
import java.awt.Frame;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author HP
 */
public class EditProfileDialog extends javax.swing.JDialog {

    /**
     * Creates new form EditProfileDialog
     */
    private JTextField usernameField;
    private JPasswordField newPasswordField;
    private JPasswordField retypePasswordField;
    private JButton saveButton;
    private JButton cancelButton;

    private String originalUsername;
    private String originalPassword;
    private Cashier us;
    private ProfileUpdateListener profileUpdateListener;

    public EditProfileDialog(Frame owner, String username, String password, ProfileUpdateListener listener) {
        super(owner, "Edit Profile", true);
        this.originalUsername = username;
        this.originalPassword = password;
        this.us = new Cashier(username, password, "Cashier");
        this.profileUpdateListener = listener;
        initCustomComponents();
    }

    private void initCustomComponents() {
        // Set the layout and size of the dialog
        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);

        // Username Field
        gbc.gridx = 0;
        gbc.gridy = 0;
        add(new JLabel("Username:"), gbc);

        usernameField = new JTextField(originalUsername);
        gbc.gridx = 1;
        gbc.gridy = 0;
        add(usernameField, gbc);

        // New Password Field
        gbc.gridx = 0;
        gbc.gridy = 1;
        add(new JLabel("New Password:"), gbc);

        newPasswordField = new JPasswordField();
        gbc.gridx = 1;
        gbc.gridy = 1;
        add(newPasswordField, gbc);

        // Retype Password Field
        gbc.gridx = 0;
        gbc.gridy = 2;
        add(new JLabel("Retype Password:"), gbc);

        retypePasswordField = new JPasswordField();
        gbc.gridx = 1;
        gbc.gridy = 2;
        add(retypePasswordField, gbc);

        // Save Button
        saveButton = new JButton("Save");
        saveButton.addActionListener(e -> saveProfile());
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.CENTER;
        add(saveButton, gbc);

        // Cancel Button
        cancelButton = new JButton("Cancel");
        cancelButton.addActionListener(e -> dispose());
        gbc.gridx = 1;
        gbc.gridy = 3;
        add(cancelButton, gbc);

        pack();
        setLocationRelativeTo(getOwner());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void saveProfile() {
        String newUsername = usernameField.getText();
        String newPassword = new String(newPasswordField.getPassword());
        String retypePassword = new String(retypePasswordField.getPassword());

        if (newPassword.equals(retypePassword)) {
            if (newPassword.isEmpty()) {
                newPassword = originalPassword;
            }

            us.updateUserProf(originalUsername, newUsername, newPassword);
            System.out.println("Profile updated: " + newUsername + ", Password: " + newPassword);

            if (profileUpdateListener != null) {
                profileUpdateListener.onProfileUpdated(newUsername);
            }
            dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Passwords do not match.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    public static void main(String[] args) {
        try {
            SwingUtilities.invokeLater(() -> {
                
                JFrame frame = new JFrame();
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setSize(800, 800);
                frame.setVisible(true);

                // Create and display the EditProfileDialog with a listener
                EditProfileDialog dialog = new EditProfileDialog(frame, "currentUsername", "currentPassword", newUsername -> {
                    
                    //System.out.println("Profile updated with new username: " + newUsername);
                    
                });
                dialog.setVisible(true);
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
